server:
  port: 18092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.175.128
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.175.128
    virtual-host: /jiange
    username: jiange
    password: jiange
feign:
  sentinel:
    enabled: true
jwt:
  pubKeyPath: E:\0821Java\learn\IdeaProject\RSA\rsa.pub
  cookieName: GMALL-TOKEN
  expire: 8640000