server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.175.128
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.175.128:3306/guli_cart
    username: root
    password: 123456Abc@
feign:
  sentinel:
    enabled: true
jwt:
  pubKeyPath: E:\0821Java\learn\IdeaProject\RSA\rsa.pub
  cookieName: GMALL-TOKEN
  userKey: userKey
  expire: 8640000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto