server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.175.128
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
jwt:
  pubKeyPath: E:\0821Java\learn\IdeaProject\RSA\rsa.pub
  priKeyPath: E:\0821Java\learn\IdeaProject\RSA\rsa.pri
  secret: 30489ouerweljrLROE@#)(@$*343jlsdf
  expire: 180
  cookieName: GMALL-TOKEN
  unick: unick